# This is a basic workflow to help you get started with Actions

name: smx-updater

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push: 
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  s1-dispatcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2
      
      - name: dispatching
        uses: appleboy/scp-action@master
        with:
          host: s1.csgowiki.top
          username: csgo
          password: ${{ secrets.PASSWORD_S1 }}
          source: "plugins/*"
          target: "steamcmd/games/csgo/csgo/addons/sourcemod/"
  s2-dispatcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2
      
      - name: dispatching
        uses: appleboy/scp-action@master
        with:
          host: s2.csgowiki.top
          username: csgo
          password: ${{ secrets.PASSWORD_S2 }}
          source: "plugins/*"
          target: "steamcmd/games/csgo/csgo/addons/sourcemod/"
  s3-dispatcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2
      
      - name: dispatching
        uses: appleboy/scp-action@master
        with:
          host: s3.csgowiki.top
          username: csgo
          password: ${{ secrets.PASSWORD_S3 }}
          source: "plugins/*"
          target: "steamcmd/games/csgo/csgo/addons/sourcemod/"
  s4-dispatcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2
      
      - name: dispatching
        uses: appleboy/scp-action@master
        with:
          host: s4.csgowiki.top
          username: csgo
          password: ${{ secrets.PASSWORD_S4 }}
          source: "plugins/*"
          target: "steamcmd/games/csgo/csgo/addons/sourcemod/"
  s5-dispatcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2
      
      - name: dispatching
        uses: appleboy/scp-action@master
        with:
          host: s5.csgowiki.top
          username: csgo
          password: ${{ secrets.PASSWORD_S5 }}
          source: "plugins/*"
          target: "steamcmd/games/csgo/csgo/addons/sourcemod/"
  s6-dispatcher:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-repo
        uses: actions/checkout@v2
      
      - name: dispatching
        uses: appleboy/scp-action@master
        with:
          host: s6.csgowiki.top
          username: csgo
          password: ${{ secrets.PASSWORD_S6 }}
          source: "plugins/*"
          target: "steamcmd/games/csgo/csgo/addons/sourcemod/"